#!/bin/python3

import os, sys

MAIN_FNAME = "main.c"
SRC_PATH   = "lib/src"
OUT_FNAME  = "outp"

_COMPILE_FLAGS = [
	"-static",
	"-masm=intel",
	"-nostdlib",
	"-Wno-builtin-declaration-mismatch"
	# "-z noexecstack",
]
COMPILE_FLAGS = " ".join(_COMPILE_FLAGS)

CMD = f"cc {COMPILE_FLAGS} {MAIN_FNAME} {SRC_PATH}/*.c {SRC_PATH}/*.s"

if len(sys.argv) > 1:
	match sys.argv[1]:
		case "debug":
			CMD += " -DDEBUG"
		case "asm":
			os.system(f"{CMD} -S")
			exit(0)
		case "clean":
			import glob
			for file in glob.glob("./*.s") + [f"./{OUT_FNAME}"]:
				os.remove(file) if os.path.isfile(file) else None
			exit(0)
		case _:
			print("huh")
			exit(-43)

if os.system(f"{CMD} -o {OUT_FNAME}") == 0:
	print(CMD)
	# run prog
	print("starting program:\n")
	print("----------------")
	x = os.system(f"./{OUT_FNAME}")
	print()
	print("----------------")
	print("\nfinished running\nexited with code " + str(x))
	exit(x)